package chained-service:api

interface prodcon {
   record consume-byte-request {
       value: list<u8>
   }

   record consume-byte-reply {
       value: bool,
       length: s32,
   }

   consume-byte: func(request: consume-byte-request) -> result<consume-byte-reply, s32>
   init-component: func()

}

// interface faas-component {
//    init-component: func()
// }

interface hello-world {

    record hello-request {
       name: string
    }

    record hello-reply {
        message: string
    }

    say-hello: func(request: hello-request) -> result<hello-reply, s32>
    init-component: func()
}

world producer-interface {
    export hello-world
    //export faas-component
    import prodcon
    //import faas-component
}

world consumer-interface {
    //export faas-component
    export prodcon
}

world top-level {
    //export faas-component
    export hello-world
}